In [1]:
import numpy as np
import argmax_fast
import argmax_fast_v2

In [2]:
test_data = np.random.rand(100)
# test_data = np.random.randint(0,100, 100)
test_data

array([0.28597757, 0.24273758, 0.24187402, 0.29967056, 0.83278665,
       0.88419032, 0.59317994, 0.31724489, 0.40930156, 0.05854146,
       0.49432931, 0.91487969, 0.6496355 , 0.91470159, 0.71308641,
       0.88562516, 0.08850428, 0.31728598, 0.81607808, 0.42771532,
       0.92126205, 0.58559871, 0.16630285, 0.1720364 , 0.42081355,
       0.07034486, 0.30320007, 0.62335083, 0.22695287, 0.12125752,
       0.00261901, 0.94101952, 0.24069462, 0.38455967, 0.28939664,
       0.80757966, 0.47499966, 0.75067753, 0.57076465, 0.65002913,
       0.66198184, 0.2760068 , 0.16024325, 0.61183768, 0.62219339,
       0.55561677, 0.98639201, 0.77878979, 0.38782412, 0.07589713,
       0.59071815, 0.33741149, 0.97895356, 0.7321659 , 0.77128642,
       0.00607532, 0.84891494, 0.08802227, 0.52639444, 0.76526333,
       0.86682888, 0.32384866, 0.84330822, 0.2990789 , 0.23776782,
       0.75186351, 0.69444821, 0.44748101, 0.41686379, 0.23491397,
       0.39089504, 0.04917359, 0.50692153, 0.76888176, 0.43823

In [3]:
argmax_fast_v2.argmax_1d(test_data)

array(46)

In [4]:
np.argmax(test_data)

46

In [5]:
%timeit argmax_fast_v2.argmax_1d(test_data)

1.84 µs ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
%timeit np.argmax(test_data)

2.91 µs ± 73.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
%timeit argmax_fast.argmax_1d(test_data)

464 ns ± 2.03 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
test_data = np.random.rand(500).astype(np.float64)
test_data

array([0.15063235, 0.8707323 , 0.29973082, 0.15434338, 0.71798987,
       0.7414192 , 0.20430816, 0.5601001 , 0.74158814, 0.53941479,
       0.3954821 , 0.43308665, 0.88156698, 0.40151356, 0.17090896,
       0.79253834, 0.71178245, 0.3836533 , 0.23300372, 0.84387628,
       0.23079496, 0.77030687, 0.76070262, 0.89393607, 0.80960038,
       0.52828785, 0.00615605, 0.68375488, 0.34282924, 0.84517547,
       0.90136471, 0.37987539, 0.75688999, 0.51580037, 0.0637889 ,
       0.43523002, 0.10221638, 0.83067664, 0.4644254 , 0.87036665,
       0.42482559, 0.26635693, 0.32040246, 0.51143435, 0.64068453,
       0.49343424, 0.97131499, 0.23534862, 0.6110597 , 0.59897503,
       0.17100443, 0.00406528, 0.90751553, 0.51832442, 0.45857754,
       0.75269066, 0.51879581, 0.0116328 , 0.17139733, 0.44766503,
       0.47975958, 0.2314385 , 0.26335032, 0.5169158 , 0.77929213,
       0.97040455, 0.37678752, 0.67131953, 0.9648292 , 0.34378846,
       0.65324263, 0.97404828, 0.45500126, 0.46691229, 0.35148

In [9]:
%timeit argmax_fast_v2.argmax_1d(test_data)

2.06 µs ± 7.65 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
%timeit np.argmax(test_data)

3.2 µs ± 91.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
%timeit argmax_fast.argmax_1d(test_data)

900 ns ± 5.42 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
test_data = np.random.rand(1000).astype(np.float64)
test_data

array([2.56473788e-01, 4.96395158e-01, 9.11460911e-01, 9.05558677e-01,
       3.19227300e-01, 7.38961384e-01, 2.29679214e-01, 3.80390149e-01,
       6.80464783e-01, 6.44119520e-01, 6.48717512e-01, 4.08725145e-01,
       4.00186702e-01, 2.56058244e-01, 9.39130816e-01, 5.39334070e-01,
       3.05609449e-01, 9.24273912e-01, 8.01606955e-01, 7.27186125e-01,
       3.17529758e-01, 9.14197397e-01, 8.50278090e-01, 4.08684606e-01,
       9.34188716e-01, 8.41708304e-02, 6.72154161e-01, 8.65604583e-01,
       7.24079656e-02, 9.25581968e-01, 1.89329253e-01, 7.28207613e-01,
       1.37436635e-01, 9.27794343e-01, 3.74360982e-01, 2.83103774e-01,
       8.24172279e-01, 6.61202557e-01, 9.69728383e-01, 3.28886655e-01,
       9.26909675e-01, 4.80218416e-01, 5.99306126e-01, 4.90726442e-01,
       1.69803776e-01, 4.72002664e-01, 7.18933803e-01, 3.76589955e-01,
       7.35573237e-01, 2.06493195e-01, 9.73472411e-01, 2.81053208e-01,
       3.90433729e-01, 2.13927809e-02, 6.15543548e-01, 4.31695562e-01,
      

In [13]:
%timeit argmax_fast_v2.argmax_1d(test_data)

2.42 µs ± 85.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [14]:
%timeit np.argmax(test_data)

3.48 µs ± 53.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
%timeit argmax_fast.argmax_1d(test_data)

1.46 µs ± 9.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
